import type { Metadata } from 'next';
import { Noto_Serif_Bengali } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import NavLinks from '@/components/NavLinks';

const notoSerifBengali = Noto_Serif_Bengali({
  variable: '--font-noto-serif-bengali',
  subsets: ['bengali', 'latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
 
export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html
      lang="bn"
      data-theme='light'
      className={`${notoSerifBengali.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-bengali">
        <Header />
        <NavLinks />
        {children}
      </body>
    </html>
  );
}
